### ISSUE TITLE
Feature Request: pfinterp for existing files

### ISSUE THREAD

**Issue by pgierz** [FESOM/pyfesom2#113]
Hello,

it'd be nice to use pfinterp from the command line on files that may have already been processed "by hand", e.g. with cdo:

```shell
$ cdo ymonmean -select,name=tos outdata/*tos* my_special_file.nc
$ pfinterp --use-premade-file $MESH my_special_file.nc -o my_output.nc
```

A switch like `use-premade-file` would then circumvent all the depth/timestep/etc processing. I'd try to do this myself, but Nikolay will undoubtably be faster :-)

Cheers,
Paul

**Comment by koldunovn** [comment]
Hi @pgierz 

If you can provide me with an example of such a file, I can try to implement it :)

So, what you have in mind is a generic file with 2D fields on nodes or elements?

**Comment by pgierz** [comment]
Sorry I never got around to this.

@koldunovn, here's something to try out:

```shell
# On Ollie:
$ cdo timmean /work/ollie/pgierz/PalModII/old_stuff/experiments/LGM_GLAC1D_Ctrl_001/outdata/fesom/temp.fesom.2* data_to_plot.nc
```

It'd be great if you could pre-process something with CDO, and then still put it through pfinterp...

I have one more idea, but that is a separate issue.

**Comment by koldunovn** [comment]
I am now experimenting with this in https://github.com/koldunovn/fint , which hopefully eventually become part of pyfesom2 :)

**Comment by chrisdane** [comment]
Any update on this? Would really appreciate!
