### ISSUE TITLE
How do I plot variables on the elements using pyfesom2?

### ISSUE THREAD

**Issue by dchari** [FESOM/pyfesom2#115]
* pyfesom2 version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by koldunovn** [comment]
Currently the best way is to first interpolate variables from elements to nodes with finctions `tonodes` or `tonodes3d` and then use usual plotting with interpolation to regular grid (`plot` function) or on original triangular grid (`tplot` function).
