### ISSUE TITLE
how do I get a 3d mask for the global ocean?

### ISSUE THREAD

**Issue by mozeising** [FESOM/pyfesom2#116]
* pyfesom2 version: 0.2.0
* Python version: Python 3.7.4
* Operating System: ollie

### Description

Is there an easy option to get a 3d mask instead of a 2d mask as implemented in 
mask = pf.get_mask(mesh, "Global Ocean")

**Comment by koldunovn** [comment]
Can you describe a case, where you need a 3D mask with FESOM2 data?

**Comment by mozeising** [comment]
I try to update Judith's py_recom script to python3 and cartopy, she interpolated World Ocean Atlas data to the FESOM mesh for comparison. After interpolation I want to plot only datapoints at certain depth levels where there is actually water. 
![image](https://user-images.githubusercontent.com/24455044/92377409-65e6a900-f104-11ea-8e8b-64f6301be007.png)

**Comment by koldunovn** [comment]
I guess then you are working with old FESOM1.4 data, right? The field you are showing looks very strange to me, by the way, I think something went wrong at the interpolation phase. 

Anyway, the masking only selects surface points. Then for each of the levels you have to work with data, that have the same amount of points as surface data, but with points that do not exist anymore at this depth filled with NaNs. In FESOM2 and FESOM1.4 CMIP6 version this is done automatically (output is already organised this way). In old FESOM1.4 by default it's not the case, but for each level you can create data in this form (same size as surface, but with NaNs at missing points) with use of pyfesom (https://github.com/FESOM/pyfesom/blob/bf7062c9577a67ec47d0fbba567d4e2758a776a0/pyfesom/load_mesh_data.py#L543).

**Comment by mozeising** [comment]
I worked with FESOM2-REcoM data of a small test run I did... 
The interpolation of the World Ocean Atlas data as shown above covers the whole ocean surface area where it should be cut to bathimetry, hence be cut with a mask, I would suppose. 
I've now just applied a mask by using FESOM output in the following (not so nice) way:
```
## analysis of DIN in FESOM and WOA
# apply sea mask to WOA data to cut out non-ocean interpolation results 
# assumption: there is no ocean where value in DIN_FESOM == 0

# create copy of WOA dataset 'din_int'
din_int_ma = np.copy(din_int) 
# mask data
din_int_ma[DINfesom == 0] = 0
```

![image](https://user-images.githubusercontent.com/24455044/92393715-99cfc780-f120-11ea-9cef-bb883335f3fc.png)

**Comment by koldunovn** [comment]
I did not get that it was from 6000 meters :)
No, there is no mask for each depth level, so the way you did, masking according to fesom mesh, is ok.

To compare to climatology I usually also interpolate climatology to FESOM grid, which makes it much more convinient to operate. The easiest way to do it, though, is to run the model from climatology initial condition for one very small timestep and output the result. We do it for temperature and salinity, but I guess FESOM2-REcoM use some initital conditions from WOA as well.

**Comment by mozeising** [comment]
okay, thanks a lot for helping!
