### ISSUE TITLE
Scalars definition: use Zlev or Z for depth

### ISSUE THREAD

**Issue by mozeising** [FESOM/pyfesom2#117]
* pyfesom2 version: 0.2.0
* Python version: 3.8.5
* Operating System: Linux Mint

### Description
I want to compare scalar values at certain depths, such as diatom carbon output of FESOM2-REcoM with observation data (e.g. MarEDAT or WOA). In Danilov et al. (2017), you describe the scalars as positioned as this: "In the vertical direction, the horizontal velocities and scalars are located at mid-levels."
Thus, I wondered what I have to use for my comparison: mesh.zlev or the variable 'Z' out of the mesh diag file, which is defined as the depth of layers aka mid-level depth. I would choose the 'Z' according to the description in the paper. Is that right?

##### load FESOM mesh ------------------------------------------------------------------------------------
mesh = pf.load_mesh(meshpath)
mesh.zlev

##### load FESOM mesh diag -------------------------------------------------------------------------------
meshdiag= resultpath+'/'+runid+'.mesh.diag.nc'
#!ncdump -h $meshdiag

diag = pf.get_meshdiag(mesh,meshdiag=meshdiag, runid=runid)
#print(diag)
#print(diag['Z']) # depth of layers
mesh_depths = diag['Z'].values

**Comment by koldunovn** [comment]
Hi @mozeising 

Yes, that is right, you would have to use `Z` (or compute it by yourself by just dividing the levels).

**Comment by mozeising** [comment]
okay, thanks for the quick answer!
