### ISSUE TITLE
How can I calculate AMOC using pyfesom2?

### ISSUE THREAD

**Issue by xshi-awi** [FESOM/pyfesom2#121]
Hello. May I ask the way to compute AMOC by pyfesom2, is there a command for this?

Thanks so much in advance.

Best
Xiaoxu

**Comment by pgierz** [comment]
Xiaoxu, could you maybe also post what you needed to use to solve this? That way @koldunovn might have a better idea what to improve in the documentation, or if what we have already is sufficient.

**Comment by xshi-awi** [comment]
Hi Paul. Thanks for your reply. I mistakenly posted 2 similar issues, sorry. @koldunovn has answered me in another issue. The documentation on the AMOC calculation is clear to me, thanks.
