### ISSUE TITLE
AMOC calculation

### ISSUE THREAD

**Issue by xshi-awi** [FESOM/pyfesom2#122]
Hello. May I ask the way to compute AMOC by pyfesom2, is there a command for this?

Thanks so much in advance.

Best
Xiaoxu

**Comment by koldunovn** [comment]
Hi @xshi-awi 

Here is the notebook with explanation on how to do it: https://github.com/FESOM/pyfesom2/blob/master/notebooks/compute_MOC.ipynb

**Comment by xshi-awi** [comment]
Thanks. My data are on mistral. I found I can not install pyfesom2 using conda as I do not have writing permission to root folders. How can I install pyfesom2 as a python package on mistral? Many thanks.

**Comment by xshi-awi** [comment]
Many thanks. 

Best
Xiaoxu
