### ISSUE TITLE
pf.plot() with rotated mesh

### ISSUE THREAD

**Issue by LAWTIDEBOY** [FESOM/pyfesom2#125]
* pyfesom2 version:  0.2.0
* Python version: 3.7.7
* Operating System: Ollie0

### Description

Dear, maybe I am missing something, by when trying to use the pyfesom2 plot() function, it does not consider the rotation angles from the mesh, obviously resulting in wrong positioning of nodes. I do NOT have this issue with tplot() which works just fine with rotated mesh.

![Screenshot 2021-01-21 at 11 21 42](https://user-images.githubusercontent.com/38709425/105337614-e3eeac80-5bda-11eb-9d5e-17159a4c5f2d.png)
![Screenshot 2021-01-21 at 11 21 52](https://user-images.githubusercontent.com/38709425/105337625-e51fd980-5bda-11eb-97ac-b4ae31a0d941.png)

Here are the mesh caracteristics:

FESOM mesh:
path                  = /work/ollie/loziel/mesh/core2_meanz
alpha, beta, gamma    = 50, 15, -90
number of 2d nodes    = 126858
number of 2d elements = 244659

### What I Did

mesh = pf.load_mesh('/work/ollie/loziel/mesh/core2_meanz/', abg = [50, 15, -90], usepickle=True, usejoblib=False, protocol=4)
datapath = "/work/ollie/loziel/model_output/fesom2-test3/"
data = pf.get_data(datapath, "sst", 1948, mesh)
pf.plot(mesh, data[:]) # this does not work
pf.tplot(mesh, data[:]) # this works fine

**Comment by koldunovn** [comment]
Hi @LAWTIDEBOY 

In some place the mesh and data rotation are inconsistent. I was able to plot properly with this mesh:
mesh = pf.load_mesh('/work/ollie/nkolduno/meshes/POOL/meshes/core2/',  usepickle=False, usejoblib=False, protocol=4)

According to your `/work/ollie/loziel/model_output/fesom2-test3/fesom.mesh.diag.nc` for computations you used unrotated `core` mesh (which is great), but you try to use old rotated `core` mesh for plotting.

**Comment by LAWTIDEBOY** [comment]
Thank you very much Nikolay, sorry for the confusion.
It is because I actually ran the model with the "old rotated mesh" (/work/ollie/loziel/mesh/core2_meanz)
So I did not expect to have an unrotated field in the output.
Sorry about that, this issue can be closed :)

**Comment by koldunovn** [comment]
@LAWTIDEBOY 

As far as I understand you actually run the model with unrotated mesh, this is what I get from your `fesom.mesh.diag.nc`, which is the "ultimate truth" about what exactly you were using for computation. So maybe doublecheck what exactly you use. Currently results in `/work/ollie/loziel/model_output/fesom2-test3/` are produced with unrotated mesh, not the `/work/ollie/loziel/mesh/core2_meanz/`, which is rotated.

**Comment by LAWTIDEBOY** [comment]
Thank Nikolay,

I am still confuse I must admit. 

The mesh I use for running the model is rotated (not good I know I will change that) and is a copy of 
'MeshPath='/work/ollie/pscholz/mesh_fesom2.0/core2_meanz/'

My namelist.config is the following:

&geometry
cartesian=.false.
fplane=.false.
cyclic_length=360       ![degree]
rotated_grid=.true.     !option only valid for coupled model case now
force_rotation=.false.
alphaEuler=50.          ![degree] Euler angles, convention:
betaEuler=15.           ![degree] first around z, then around new x,
gammaEuler=-90.         ![degree] then around new z.
/

**Comment by koldunovn** [comment]
You are right, something is not right... Looking into it.

**Comment by pgierz** [comment]
From the esm team: anything I need to look into? Give a sign if that is the case.

**Comment by koldunovn** [comment]
I think I get it :) When we use `plot`, we interpolate data. To do this efficiently, we save interpolation weights ether in mesh folder, if you have acces to it, or in `MESH_cache` directory of the current working directory. If the files are already created, they will be reused. If they were created with wrong mesh rotation settings, they will not be recreated when you fix the rotation. So, the solution should be to delete `distances_126858*` and `inds_126858*` files from the `/home/ollie/nkolduno/PYTHON/MESH_cache/core2_meanz`. The `tplot` does not use interpolation, so it works as expected.

Let me know if it solves the issue.

**Comment by koldunovn** [comment]
> From the esm team: anything I need to look into? Give a sign if that is the case.

Thanks for offering help, @pgierz ! I hope we solve it now 🤞 .

**Comment by LAWTIDEBOY** [comment]
Victory !!

I do confirm It works now. 
I probably entered wrong or no angles the first time :/

You rock Nikolay ! Thank so much 👍
