### ISSUE TITLE
Colorbar

### ISSUE THREAD

**Issue by dchari** [FESOM/pyfesom2#127]
* pyfesom2 version:
* Python version:
* Operating System

I created the ax by f, ax=plt.subplots(1,1) and gave this to my plot function in order to set the x boundaries, and because of this the colorbar would not show up anymore. 
Is there a simpler method to set the x value boundaries in another way without losing the colorbar ?or if there is a way to create the colorbar after plotting?

**Comment by koldunovn** [comment]
@dchari Can you, please, describe your problem in more detail, better with the minimum example that I can reproduce. From you description it's not clear what you trying/want to do.

General comment:
I would say that if you want to customize the plots, it's easier just to create the code from scratch, using pyfesom2 code as an example. Everyone has their own taste and requirements, and pyfesom2 plotting functions should only be used as a quick-view. Their look is very basic, and not suitable (and not intended) for publication, for example.
Saying that I plan to work on better ways to return image object that the user then can modify, but it will take time.

**Comment by koldunovn** [comment]
Close for inactivity.
