### ISSUE TITLE
Unable to change the color label

### ISSUE THREAD

**Issue by StanleyAgu1** [FESOM/pyfesom2#128]
I have a problem with the color label.

I want to remove the white color of the planets on my plot, but I keep getting errors. this is my script

`def plot_holoviews(mesh, data, wireframe=False, cmap=None, proj='pc', data_name='data',clabel=None, levels=None):
    
    
    elem2 = mesh.elem[mesh.no_cyclic_elem]
    data = np.ma.masked_equal(data, 0)
    
    verts = pd.DataFrame({'Longitudes':mesh.x2, 'Latitudes':mesh.y2, 'data':data})
    tris = pd.DataFrame({'v0':elem2[:,0],'v1':elem2[:,1], 'v2':elem2[:,2]})
    fesom_mesh = gv.TriMesh((tris, verts), crs=crs.PlateCarree())
    if wireframe:
        verts2 = pd.DataFrame({'Longitudes':mesh.x2, 'Latitudes':mesh.y2})
        trimesh = gv.TriMesh((tris, verts2), crs=crs.PlateCarree())
        wireframe_plot = datashade(trimesh, interpolation=None, cmap=['black'])
    
    if proj == 'pc':
        projection=crs.PlateCarree()
        width=800,
        height=500,
        y_range=(-80,90)
    elif proj == 'np':
        projection=crs.NorthPolarStereo()
        width = 500,
        height = 500,
        y_range=(60,90)
    elif proj == 'sp':
        projection=crs.SouthPolarStereo()
        width = 500,
        height = 500,
        y_range=(-90,-30)
    
    if cmap is None:
        cmap=cmo.balance
        
    main_plot = rasterize(fesom_mesh, interpolation=None, y_range=y_range).opts(
                        tools=["hover"],
                        width=width[0],
                        height=height[0],
                       #    projection=projection,
                        colorbar=True,
                        cmap=cmap,
                        colorbar_position="bottom",
                        clabel=clabel,
                        fontscale=1.3,
                        color_levels=levels
                    )
    if wireframe:
        return main_plot * gv.feature.coastline() * wireframe_plot
    else:
        return main_plot * gv.feature.coastline()`

After Loading my data, I did this;

`levels=[-5,-4,-3,-2,-1,0,1,2,3,4,5]` and the this;
`plot_holoviews(mesh, data0, clabel="sea surface temperature", levels=levels)`

I don't know what the problem is, can someone help me with this?

Thank you

**Comment by koldunovn** [comment]
Can only repeat what I said here :) 
https://github.com/FESOM/pyfesom/issues/14#issuecomment-778269937

**Comment by StanleyAgu1** [comment]
> Can only repeat what I said here :)
> [FESOM/pyfesom#14 (comment)](https://github.com/FESOM/pyfesom/issues/14#issuecomment-778269937)

I'm trying to make modifications to my fesom restart file on Jupyter Notebook. see the attached file, I want to change the white places so that I can clearly see the changes I made.

<img width="1153" alt="Screenshot 2021-02-12 at 16 49 56" src="https://user-images.githubusercontent.com/73535862/107789872-6f7ad980-6d52-11eb-8a01-ef71d07d0d6b.png">

**Comment by koldunovn** [comment]
Sorry I still don't get what you are trying to do :( @pgierz maybe you have any thoughts?

**Comment by pgierz** [comment]
Hi, I can look in detail tomorrow or Monday. Perhaps to better understand: you want the continents black, or grey, and then only have white where there is 0 change?

Geoviews uses bokeh syntax in the background, and I might be too old school to know a solution off the top of my head. For matplotlib I could tell you

**Comment by pgierz** [comment]
Hi @StanleyAgu1, I have some time tomorrow afternoon to look at this. Can you please post (or send me a link, email is fine too) to the following:

* Notebook you are using
* Any data that is loaded
* Any CDO/Shell preprocessing you do before hand

Nikolay, do you know if we have a NBViewer installed at AWI yet? If not, I can let the computing center guys know, that might be useful to have...

**Comment by koldunovn** [comment]
@pgierz I don't think so. I usually just connect to ollie with running notebook server and look a everything (including images, which is very convenient :))

**Comment by StanleyAgu1** [comment]
> Hi @StanleyAgu1, I have some time tomorrow afternoon to look at this. Can you please post (or send me a link, email is fine too) to the following:
> 
> * Notebook you are using
> * Any data that is loaded
> * Any CDO/Shell preprocessing you do before hand
> 
> Nikolay, do you know if we have a NBViewer installed at AWI yet? If not, I can let the computing center guys know, that might be useful to have...

Hi @pgierz thanks. this is the link to the notebook.

https://jupyterhub.dkrz.de/user/a270162/preset/notebooks/pf/a/a270162/Master-Thesis-StanleyAgu/template_plot_fesom2_data.ipynb 

This is the loaded file /work/ba1006/a270151/esm-experiments/shiloh/restart/fesom/fesom.3300.oce.restart.nc

sorry for the late response

**Comment by koldunovn** [comment]
Please reopen if the problem is not solved.
