### ISSUE TITLE
acessor data, wrong coordinates and missing data

### ISSUE THREAD

**Issue by koldunovn** [FESOM/pyfesom2#135]
I notice a couple of strange things when loading local data with accessor. The following code:

```python
import pyfesom2 as pf
d = pf.open_dataset('/work/ollie/nkolduno/output_dens_flux/*temp*', '/work/ollie/clidyn/FESOM2/meshes/core2/')
```

Result in:
<img width="788" alt="Screenshot 2021-04-30 at 17 33 26" src="https://user-images.githubusercontent.com/3407313/116718384-314c9800-a9da-11eb-87ef-a3abaed3592e.png">

The `nz1` dimension is wrong and contains wrong values.

Also the `temp` variable contains `nan`s up until 47th level.

**Comment by koldunovn** [comment]
One more thing:

`d.faces` - exclude cyclic elements. It's good for plotting, but not so nice for data analysis. We have to discuss what to keep. I would rather go for excluding cyclic elements during plotting itself, not to hide this info from the user.

**Comment by suvarchal** [comment]
> I notice a couple of strange things when loading local data with accessor. The following code:
> 
> ```python
> import pyfesom2 as pf
> d = pf.open_dataset('/work/ollie/nkolduno/output_dens_flux/*temp*', '/work/ollie/clidyn/FESOM2/meshes/core2/')
> ```
> 
> Result in:
> <img alt="Screenshot 2021-04-30 at 17 33 26" width="788" src="https://user-images.githubusercontent.com/3407313/116718384-314c9800-a9da-11eb-87ef-a3abaed3592e.png">
> 
> The `nz1` dimension is wrong and contains wrong values.
> 
> Also the `temp` variable contains `nan`s up until 47th level.

It is coming from merging level information from different sources having different sign convention for depth: one from model data itself, and other from aux3d. Could have a simple fix by forcing to a  convention of -ve values for depth or should we fix it in model output itself? or both?

**Comment by koldunovn** [comment]
I would just force vertical coordinates to be always positive.

**Comment by suvarchal** [comment]
> One more thing:
> 
> `d.faces` - exclude cyclic elements. It's good for plotting, but not so nice for data analysis. We have to discuss what to keep. I would rather go for excluding cyclic elements during plotting itself, not to hide this info from the user.

I was aware of this choice made to suit my inexperience in using cyclic face data in any analysis ;). We should discuss this on another thread maybe, meanwhile i would like to take up a problem which uses  these cyclic faces in analysis that would force me to think on what might be best to do.

**Comment by suvarchal** [comment]
> I would just force vertical coordinates to be always positive.

For example, here is level information from 3 different sources:

1. Trunctated ncdump from a sample model output:
```
netcdf temp.fesom.1948 {
dimensions:
	nz1 = 47 ;
	nod2 = 126858 ;
	time = UNLIMITED ; // (1 currently)
variables:
	double nz1(nz1) ;
		nz1:long_name = "depth at layer midpoint" ;
		nz1:units = "m" ;
		nz1:positive = "down" ;
		nz1:axis = "Z" ;
.....
data:

 nz1 = 2.5, 7.5, 15, 25, 35, 45, 55, 65, 75, 85, 95, 107.5, 125, 147.5, 175, 
    210, 255, 310, 375, 450, 535, 630, 735, 850, 975, 1110, 1255, 1415, 1600, 
    1810, 2035, 2275, 2525, 2775, 3025, 3275, 3525, 3775, 4025, 4275, 4525, 
    4775, 5025, 5275, 5525, 5825, 6125 ;
}
```

2. Truncated ncdump  from mesh diag file:

```
netcdf fesom.mesh.diag {
dimensions:
	nod_n = 126858 ;
	edg_n = 371644 ;
	elem_n = 244659 ;
	nl = 48 ;
	nl1 = 47 ;
	n2 = 2 ;
	n3 = 3 ;
	n4 = 4 ;
	N = 9 ;
variables:
	double zbar(nl) ;
		zbar:long_name = "depth of levels" ;
	double Z(nl1) ;
...
data:

 Z = -2.5, -7.5, -15, -25, -35, -45, -55, -65, -75, -85, -95, -107.5, -125, 
    -147.5, -175, -210, -255, -310, -375, -450, -535, -630, -735, -850, -975, 
    -1110, -1255, -1415, -1600, -1810, -2035, -2275, -2525, -2775, -3025, 
    -3275, -3525, -3775, -4025, -4275, -4525, -4775, -5025, -5275, -5525, 
    -5825, -6125 ;
}
```
3. First few lines from aux3d.out:
```
48
0.0
-5.0
-10.0
-20.0
-30.0
-40.0
-50.0
-60.0
-70.0
-80.0
-90.0
-100.0

```

So you prefer +ve values but add the information of sign convention as positive down in the metadata?  like in 1. above.

**Comment by koldunovn** [comment]
Yes :) The reason we have positive and negative values is that internally in the model all depths are used as positive numbers, and while reading from aux3d.out we simply apply `mod` to them. Positive values also have much more sense during computations (e.g. integrals).
