### ISSUE TITLE
`faces` in xarray accessor exclude cyclic elements

### ISSUE THREAD

**Issue by koldunovn** [FESOM/pyfesom2#136]
Currently `faces` in xarray accessor  - exclude cyclic elements. It's good for plotting, but not so nice for data analysis. We have to discuss what to keep. I would rather go for excluding cyclic elements during plotting itself, not to hide this info from the user.

**Comment by koldunovn** [comment]
Here is an example of a function that use all nodes: https://github.com/FESOM/pyfesom2/blob/a2951ced1ead4e02ad015a62d6f7b8512b2c5bb2/pyfesom2/regridding.py#L661

Anyway by cutting down the elements we don't provide the complete data to the user. I think whether or not cyclic points should be excluded should be decided on (plotting) function level, not at the dataset level.

**Comment by suvarchal** [comment]
it is fixed in #134 , but more work to go in that PR.
