### ISSUE TITLE
Option to give back Xarray Object in xmoc_data

### ISSUE THREAD

**Issue by pgierz** [FESOM/pyfesom2#138]
Hello,

I am trying to use the diagnostic xmoc_data with Xarray data:

```python
import xarray
import pyfesom2 as pf2

def _pf_xmoc_swap_args(da, mesh, **kwargs):
    """Needed since map in groupby expects the dataset first. xmoc_data wants the mesh first"""
    return pf2.diagnostics.xmoc_data(mesh, da, **kwargs)

mfds = xr.open_mfdataset("/path/to/fesom/out/w.fesom.*nc", use_cftime=True)
mesh = pf2.load_mesh("/my/super/awesome/mesh")
w = mfds.w
amoc = w.groupby("time").map(_pf_xmoc_swap_args, args=(mesh,))  # Yes, (mesh,) with a comma. It needs to be tuple.
```

Looks easy enough. Plus it's Dask in the background, so you can push it to a cluster easily. Cool stuff.

However...

```
  File "/pf/a/a270077/conda-envs/mis3/lib/python3.8/site-packages/xarray/core/groupby.py", line 803, in map
    return self._combine(applied, shortcut=shortcut)
  File "/pf/a/a270077/conda-envs/mis3/lib/python3.8/site-packages/xarray/core/groupby.py", line 823, in _combine
    coord, dim, positions = self._infer_concat_args(applied_example)
  File "/pf/a/a270077/conda-envs/mis3/lib/python3.8/site-packages/xarray/core/groupby.py", line 464, in _infer_concat_args
    if self._group_dim in applied_example.dims:
AttributeError: 'tuple' object has no attribute 'dims'
```

I almost thought I had uncovered a Xarray bug, until I discovered

https://github.com/FESOM/pyfesom2/blob/a2951ced1ead4e02ad015a62d6f7b8512b2c5bb2/pyfesom2/diagnostics.py#L453

Merp :-(

It turns out though, that the "combine" step of groupby split/apply/combine expects a data array to come back.

Would it be challenging to allow the diagnostic functions to give back Xarray objects? I can have a look at the `xmoc_data` and might send a PR if I can hack something together.

**Comment by koldunovn** [comment]
@pgierz Sure! Let's do it through the flag maybe? Can you do a PR?

I haven't heard of doing it through map, thanks for the hint! :)

**Comment by pgierz** [comment]
Yeah, I'll do something like `returnXarray=False` as the default so the normal behavior doesn't change. Do you know the shape of `moc_final`? I guess it should be number of levels?

**Comment by koldunovn** [comment]
Yes, should be number of levels by lats (or other way round ). Can you also, please, add tests here https://github.com/FESOM/pyfesom2/blob/a2951ced1ead4e02ad015a62d6f7b8512b2c5bb2/tests/test_diagnostics.py ?

**Comment by pgierz** [comment]
See #139. 

For testing, I just recycled the last test, since Xarray objects have the same mean, min,max functionality. The numerics obviously don't change, just what's given back.
