### ISSUE TITLE
Installation HLRN VersionConflict

### ISSUE THREAD

**Issue by FinnHeu** [FESOM/pyfesom2#164]
### Description

Hi, 
when trying to install pyfesom2 on the HLRN systems I get a version conflict that I can't solve. 
I have created the conda environment from the requirements-py37.yml file but when trying to install pyfesom2 in development mode using ``` pip install -e .``` I run into some version conflict between Xarray and Pandas (see screenshot). When checking my pandas version by running ```conda list``` I get ``` pandas            1.3.4            py39hde0f152_1    conda-forge ```which should satisfy pandas >= 1.0. Any idea how to solve this? 
Cheers, Finn

![Bildschirmfoto 2021-12-06 um 11 04 19](https://user-images.githubusercontent.com/57488986/144827228-58760047-b677-4641-92f1-9585b9426374.png)

**Comment by koldunovn** [comment]
Please reopen if still not solved.
