### ISSUE TITLE
no_pi_mask option for plot_vector()

### ISSUE THREAD

**Issue by haknahl** [FESOM/pyfesom2#171]
Would it be possible to add an option for no_pi_mask=True/False in plot_vector() to suppress the PI land-sea-mask in the plot?
I would like to do a deep time u and v plot with only my deep time land-sea-mask.

**Comment by pgierz** [comment]
This could be part of the general cleanup phase which we want to have (once all of us have time, @koldunovn please have Thomas reserve a tropical island for us for a week) I will put it on my list; but as a provisional solution you can always hard-code it. Not elegant, I know...

**Comment by pgierz** [comment]
Hanna, can you give me a test file to use for my plotting fixes?

**Comment by haknahl** [comment]
Ok, thank you!
Yes, sure, you find a notebook here: /home/ollie/haknahl/model_outdata/Eocene2xCO2noice/Eo2xCO2_try2+/outdata/fesom/plot_vector_example.ipynb

**Comment by koldunovn** [comment]
There is now `no_pi_mask` option in `get_vector_forplot` function, so this should be covered. Please reopen if you feel it's not adressed.
