### ISSUE TITLE
import read_fesom_slice problem

### ISSUE THREAD

**Issue by Mccino** [FESOM/pyfesom2#175]
* pyfesom2 version: pyfesom2-0.2.0
* Python version: Python 3.9.0
* Operating System: Levante

### Description
Hi, I met some problems and I don't know if there are any updates for the pyfesom2

The error message is:
**cannot import name '_read_fesom_slice_' from '_pyfesom2_'**

### What I Did

```

 I tried to compute and plot MOC following the example:
[](https://pyfesom2.readthedocs.io/en/test_updates_to_docs/notebooks/plot_main.html)
```

**Comment by koldunovn** [comment]
Do you still have the problem?

**Comment by Mccino** [comment]
> Do you still have the problem?

yes, the problem is still there

**Comment by Mccino** [comment]
Thank you very much.
I will work on these you shared.
