### ISSUE TITLE
missing 1 required positional argument: 'semiminor_axis'

### ISSUE THREAD

**Issue by qishufio** [FESOM/pyfesom2#204]
* pyfesom2 version: 0.1.0
* Python version: 3.10.12
* Operating System: Linux

When calling the function pf.cross_section_transport, the new version (3.0.1) of pymap3d may lead to this error:

File "/albedo/work/user/qishu001/env/pyfesom2/lib/python3.10/site-packages/pyfesom2/transport.py", line 753, in _ComputeBrokenLineSegments
    ell=pm.utils.Ellipsoid('wgs84')
TypeError: Ellipsoid.__init__() missing 1 required positional argument: 'semiminor_axis'

### What I Did

To fix this issue, DOWNGRAD the version of pymap3d  from 3.0.1 to 2.9.1 please.

**Comment by koldunovn** [comment]
looks like #199 fixed exactly this issue...
